### ISSUE TITLE
make step fails

### ISSUE THREAD

**Issue by ahundt** [jorisv/Eigen3ToPython#3]
I tried installing Eigen3ToPython on my machine and it failed to compile. Here is a full debug output of my attempt, it happens to be on OS X:

https://gist.github.com/648adc5988763504f16e95cd0c87ca2a

the biggest issues seem to be in the linker step which begin as follows (details in link above):

```

[100%] Linking CXX shared module eigen3/_eigen3.so
cd /Users/athundt/source/git/jorisv/Eigen3ToPython/build/src && /usr/local/Cellar/cmake/3.5.2/bin/cmake -E cmake_link_script CMakeFiles/_eigen3.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -Wall -Wextra -std=c++0x -pedantic  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion -bundle -Wl,-headerpad_max_install_names  -o eigen3/_eigen3.so CMakeFiles/_eigen3.dir/eigen3.cpp.o
Undefined symbols for architecture x86_64:
  "_PyBool_FromLong", referenced from:
      _wrap_PyEigenQuaterniond_isApprox__0(PyEigenQuaterniond*, _object*, _object*, _object**) in eigen3.cpp.o
      _wrap_PyEigenQuaterniond_isApprox__1(PyEigenQuaterniond*, _object*, _object*, _object**) in eigen3.cpp.o
  "_PyErr_Clear", referenced from:
      EigenVector2d__nb_add(_object*, _object*) in eigen3.cpp.o
      EigenVector2d__nb_subtract(_object*, _object*) in eigen3.cpp.o
      EigenVector2d__nb_multiply(_object*, _object*) in eigen3.cpp.o
      EigenVector2d__nb_divide(_object*, _object*) in eigen3.cpp.o
      EigenVector2d__nb_negative(_object*) in eigen3.cpp.o
      EigenVector2d__nb_inplace_add(_object*, _object*) in eigen3.cpp.o
      EigenVector2d__nb_inplace_subtract(_object*, _object*) in eigen3.cpp.o
      ...
```

I'm using eigen 3.2.8 so I'm a bit surprised by the errors, as I use the types being referenced in the errors frequently. Any help would be very much appreciated!

My python and pybindgen versions may also be of note:

```
± python --version
Python 2.7.11

± pip show pybindgen
---
Metadata-Version: 1.0
Name: PyBindGen
Version: 0.17.0
Summary: Python Bindings Generator
Home-page: https://launchpad.net/pybindgen
Author: Gustavo Carneiro
Author-email: gjcarneiro@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires:
Classifiers:

```

**Comment by ahundt** [comment]
I see that a specific version of pybindgen is required:

PyBindGen = 0.16 (build with 0.17 but a bug in this version prevents the use of len() on Eigen3 matrix)

However this doesn't appear to be the source of my problem.

**Comment by jorisv** [comment]
Hello,

Apparently Clang don't find the python library and then fail to link all python method.
Since your log clearly show that python library is found (PYTHON_LIBRARY:FILEPATH=/usr/lib/libpython2.7.dylib in CMakeCache.txt) I think the error is in the CMakeLists.txt.

Can you add
```cmake
target_link_libraries(_eigen3 ${PYTHON_LIBRARY})
```
At line 40 of src/CMakeLists.txt (It must be after `ADD_LIBRARY(_eigen3 MODULE ${SOURCES})`) ?
Then clear you build directory, run cmake again and try to compile.

Thank you.

**Comment by ahundt** [comment]
that fixed it! I'll submit a pull request in a few seconds. This seems to apply to a number of other libraries needed for http://github.com/jorisv/Tasks as well.

**Comment by jorisv** [comment]
Perfect,
If you can submit a PR for SpaceVecAlg, RBDyn and Tasks I would be happy to merge it.
